export const contacts = {
  GET_ALL: 'GET_ALL',
  SEARCH: 'SEARCH',
  CLEAR_SEARCH: 'CLEAR_SEARCH',

  GET_ALL_ERROR: 'GET_ALL_ERROR',
  SEARCH_ERROR: 'SEARCH_ERROR',
  CLEAR_SEARCH_ERROR: 'CLEAR_SEARCH_ERROR'
}